// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPZO2snNxm4Rc8gPceb-RjlNSPzQSa5k',
    appId: '1:517171824449:web:7a960ceffaef145a3cc3c0',
    messagingSenderId: '517171824449',
    projectId: 'shagaya-mvp',
    authDomain: 'shagaya-mvp.firebaseapp.com',
    storageBucket: 'shagaya-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5kf8GsCz__9Z8K-v0aBduX2YrIBqD-o',
    appId: '1:517171824449:android:89ceb5d7697227913cc3c0',
    messagingSenderId: '517171824449',
    projectId: 'shagaya-mvp',
    storageBucket: 'shagaya-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUsJrhsh3jYgCSpKRNxRClJ2ZgHVcdag',
    appId: '1:517171824449:ios:5b23d5bb620360533cc3c0',
    messagingSenderId: '517171824449',
    projectId: 'shagaya-mvp',
    storageBucket: 'shagaya-mvp.firebasestorage.app',
    iosBundleId: 'com.example.shagayaMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmUsJrhsh3jYgCSpKRNxRClJ2ZgHVcdag',
    appId: '1:517171824449:ios:5b23d5bb620360533cc3c0',
    messagingSenderId: '517171824449',
    projectId: 'shagaya-mvp',
    storageBucket: 'shagaya-mvp.firebasestorage.app',
    iosBundleId: 'com.example.shagayaMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPZO2snNxm4Rc8gPceb-RjlNSPzQSa5k',
    appId: '1:517171824449:web:3e921773095695f03cc3c0',
    messagingSenderId: '517171824449',
    projectId: 'shagaya-mvp',
    authDomain: 'shagaya-mvp.firebaseapp.com',
    storageBucket: 'shagaya-mvp.firebasestorage.app',
  );

}