import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'package:firebase_core/firebase_core.dart';

// If you already ran flutterfire configure, this file exists.
// If it doesn't yet, comment the next import + the DefaultFirebaseOptions usage.
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase init (requires lib/firebase_options.dart generated by flutterfire configure)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (_) {
    // Allows the app to still run even if Firebase isn't configured yet.
  }

  runApp(const ShagayaApp());
}

class ShagayaApp extends StatefulWidget {
  const ShagayaApp({super.key});

  @override
  State<ShagayaApp> createState() => _ShagayaAppState();
}

class _ShagayaAppState extends State<ShagayaApp> {
  Locale _locale = const Locale('en');

  void _toggleLocale() {
    setState(() {
      _locale = _locale.languageCode == 'en'
          ? const Locale('ar')
          : const Locale('en');
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Shagaya',
      locale: _locale,
      supportedLocales: const [Locale('en'), Locale('ar')],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.green),
      home: RoleSelectPage(onToggleLocale: _toggleLocale, locale: _locale),
    );
  }
}

class RoleSelectPage extends StatelessWidget {
  final VoidCallback onToggleLocale;
  final Locale locale;

  const RoleSelectPage({
    super.key,
    required this.onToggleLocale,
    required this.locale,
  });

  bool get isArabic => locale.languageCode == 'ar';

  String t(String en, String ar) => isArabic ? ar : en;

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: isArabic ? TextDirection.rtl : TextDirection.ltr,
      child: Scaffold(
        appBar: AppBar(
          title: Text(t('Shagaya', 'شجايا')),
          actions: [
            TextButton.icon(
              onPressed: onToggleLocale,
              icon: const Icon(Icons.language),
              label: Text(isArabic ? 'EN' : 'AR'),
            ),
          ],
        ),
        body: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 12),
              Text(
                t('Choose your account type', 'اختر نوع الحساب'),
                style: Theme.of(context).textTheme.headlineSmall,
              ),
              const SizedBox(height: 10),
              Text(
                t(
                  'This helps us match supply and demand directly between farmers and buyers.',
                  'هذا يساعدنا على الربط المباشر بين المزارعين والمشترين.',
                ),
                style: Theme.of(context).textTheme.bodyMedium,
              ),
              const SizedBox(height: 24),
              _RoleCard(
                title: t('Farmer', 'مزارع'),
                subtitle: t('Sell crops directly', 'بيع المحاصيل مباشرة'),
                icon: Icons.agriculture,
                onTap: () =>
                    _toast(context, t('Farmer selected', 'تم اختيار مزارع')),
              ),
              const SizedBox(height: 12),
              _RoleCard(
                title: t('Consumer', 'مستهلك'),
                subtitle: t('Buy from farmers', 'الشراء من المزارعين'),
                icon: Icons.shopping_basket,
                onTap: () =>
                    _toast(context, t('Consumer selected', 'تم اختيار مستهلك')),
              ),
              const SizedBox(height: 12),
              _RoleCard(
                title: t('Grocery Store', 'محل / تاجر'),
                subtitle: t('Buy in larger quantities', 'شراء بكميات أكبر'),
                icon: Icons.storefront,
                onTap: () =>
                    _toast(context, t('Grocery selected', 'تم اختيار تاجر')),
              ),
            ],
          ),
        ),
      ),
    );
  }

  static void _toast(BuildContext context, String msg) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg)));
  }
}

class _RoleCard extends StatelessWidget {
  final String title;
  final String subtitle;
  final IconData icon;
  final VoidCallback onTap;

  const _RoleCard({
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Material(
      borderRadius: BorderRadius.circular(16),
      elevation: 1,
      child: InkWell(
        borderRadius: BorderRadius.circular(16),
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              CircleAvatar(radius: 22, child: Icon(icon)),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(title, style: Theme.of(context).textTheme.titleMedium),
                    const SizedBox(height: 4),
                    Text(
                      subtitle,
                      style: Theme.of(context).textTheme.bodySmall,
                    ),
                  ],
                ),
              ),
              const Icon(Icons.chevron_right),
            ],
          ),
        ),
      ),
    );
  }
}
